### ISSUE TITLE
Harmonize terms

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-documentation#6]
Currently, for the project itself, the documentation is not consistent and the terms
- CultureApp DE
- CultureApp
- KulturApp DE
- KulturApp
- KulturApp project DE
- KulturApp DE project

are used interchangeably. In my opinion, it would be favorable to use one term throughout the whole documentation and I would be happy to provide a PR harmonizing the documentation in this regard, when I receive feedback what term(s) should be used.

**Comment by christianneu** [comment]
The official name which is approved now is "KulturPass". Therefore we should change it to this one. Also I think we don't need 'project' or 'DE' as suffixes. If you want you can start with the documentation where you can change it. I will have a look regarding the images which need to be adopted and I will speak with the devs regarding the used names in the coding.

**Comment by Ein-Tim** [comment]
@christianneu Okay, thanks for the clarification, PR will follow in the due course of this week

**Comment by GisoSchroederSAP** [comment]
There is only one exception regarding the naming: In order to differentiate the German KulturPass  from the existing Kultur Pass in Austria, we may need to use the " DE" postfix on the high level documentation (or we empasize in another way that ths is the German project). Gettings down to the details, the " DE"  could be ommitted, though.
